Dockerfile, justfile
In previous versions of the Dockerfile, we had some cool layer cache hacks to prevent the main dependency list from having to rebuild every time. I managed to partially reproduce, but not as effectively before.
What this version does is prefetch the packages (thus making a layer with the downloads already done) and then attempt to build the main libraries with an empty example (on a new layer), then building the final binaries on a last layer. This will speed up a little bit, but not as much as before.
=> fix the Dockerfile

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/kubelet/src/config.rs, crates/kubelet/src/kubelet.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/node.rs, docs/community/developers.md, justfile, src/krustlet-wascc.rs, src/krustlet-wasi.rs
This follows similar defaulting methodology as to what is found in the
normal Kubernetes kubelet. Currently we only support command line flags
and environment variables but it allows a user to configure various parts
of the kubelet
Closes #34
=> feat(kubelet): Adds ability to configure nodes

crates/kubelet/src/kubelet.rs, crates/kubelet/src/server.rs, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/lib.rs
As part of this, I changed the provider trait to instead return a vec
of bytes instead of worrying about all the allocations of copying each
line into a string. Instead the raw data is just passed back as part of
the HTTP response body.
I also found that the wasi logs implementation needed to reset the seek
pointer to the beginning of the file for future reads, so that has now
been fixed
NOTE: This is not currently tested with a running master because we do
not have HTTPS set up yet. It has been tested with manual calls to the
endpoint
Closes #33
=> feat(kubelet): Fully glues together logs logic

.github/workflows/build.yml
This PR updates our build action to also build for macOS.
It uses a simple matrix config for the operating system, and introduces a dependency on [this GitHub Action](https://github.com/marketplace/actions/engineerd-configurator) to simplify the download of `just`.
Note that testing on macOS is still failing:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(HostCallFailure(DecodeError { description: "buffer underflow", stack: [] }))', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
test test::test_wascc_run ... FAILED
failures:
---- test::test_wascc_run stdout ----
thread 'test::test_wascc_run' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:1188:5 …
```
=> Update build action to build and test on macOS and Ubuntu

docs/community/developers.md, docs/intro/tutorial01.md, docs/intro/tutorial03.md
Krustlet requires a KRUSTLET_NODE_IP to run locally or an error will occur.
=> docs(intro): set an IP address before starting krustlet

Cargo.lock, crates/oci-distribution/Cargo.toml, crates/oci-distribution/README.md, crates/oci-distribution/src/errors.rs, crates/oci-distribution/src/lib.rs, crates/oci-distribution/src/manifest.rs, crates/oci-distribution/src/reference.rs
This PR adds a crate for OCI Distribution. It has a working `version` call, and a `pull_manifest` call that hits the correct endpoint. But we need AuthZ implemented before that one will work. I have begun working on that.
We can either merge this now so that others can help, or I can keep pushing it along for a while until we get to something that meets our requirement for viability.
=> initial add of OCI Distribution crate

Cargo.lock, crates/kubelet/src/kubelet.rs, crates/wascc-provider/src/lib.rs, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/handle.rs, crates/wasi-provider/src/lib.rs, crates/wasi-provider/src/wasi_runtime.rs
Introduces the new `RuntimeHandler` type for the WASI runtime. The purpose
of this handle is to wrap all of the logic for managing the process and
getting its logs/status/etc. after it has started. Ideally, this could be
something we generalize across all providers in the future after we hammer
the kinks out. There are still some clippy warnings due to some of the code
not yet being used
Note: This also introduces some basic messaging for each "container" to
inform the provider that its status has changed
=> feat(wasi): Adds runtime handle wrapper

justfile
Based on testing from the team and what I found on the internet (always
a reliable source of information), having an empty password with a
pkcs bundle can cause errors. This exports a default password to be
used with the certificate.
Also, I removed the kubelet=debug setting for logging because kubelet is
a _really_ verbose default
=> fix(justfile): Fixes "wrong password" issue with generated certs

crates/kubelet/src/kubelet.rs
The `string_data` field of `Secret` is a write-only convenience and will always
be `None` when read.
This commit fixes it so that the `data` field is used instead.
=> Fix environment variables from secrets.

.github/workflows/build.yml
The old v1 had issues re-running builds if master had changed
=> fix(actions): Fixes GH actions checkout with version upgrade

Cargo.lock, crates/oci-distribution/Cargo.toml, crates/oci-distribution/src/lib.rs, crates/oci-distribution/src/manifest.rs, crates/oci-distribution/src/reference.rs
This adds support for _layer_ pulls on OCI images. OCI images have two artifact types that have to be pulled: manifests and layers. This adds support for pulling layers into local writers.
I am still working on this, but need help with one particular thing having to do with whether to use `tokio::io::AsyncWrite` or `std::io::Write`. Left a note inline.
The rest is not yet ready for review. Still need:
*UPDATE:* To keep this from blocking other work, I have pared it back down to the minimum. I have addressed almost all of @rylev 's comments, but have reached out to him for a follow-up PR on the AsyncWrite in the loop.
=> Add image layer pull

tests/integration_tests.rs
I know we like foos and bars...but only when they mean something
=> fix(*): Removes leftover debug code

crates/oci-distribution/src/lib.rs
Clippy was warning that we could replace the `new` method with a derived
Default. I checked reqwest and found that `Client::default()` is the
same as calling `Client::new()`. So I switched the `new` method to take
the config object and replaced the original `new` method with the derived
Default.
=> fix(oci): Fixes clippy error around default client

.github/workflows/release.yml
This commit fixes two things:
We want the release workflow to start when the tag is pushed rather than when it is published on github. That way, the release assets are ready and available when the release is published.
It turns out that you cannot have two conditional jobs with the same ID. Go figure. Instead, we now inject the release version into the environment and run the step if the reference is valid.
=> fix the release workflow

.github/workflows/release.yml
github actions runs all jobs in parallel. the publish job relies on the build job completing first before going ahead.
=> wait for build job to complete

.github/workflows/release.yml
The result of this workflow, regardless of the tagged release, will be
https://krustlet.blob.core.windows.net/releases/checksums.txt
This would result in each tagged release overwriting the checksums file.
By appending a release version to the checksum filename, we are able to differentiate between which checksum file should be used for each version.
=> fix(github): give checksums.txt a version number

docs/README.md, docs/how-to/README.md, docs/how-to/aks.md, docs/how-to/assets/generate-kubeconfig.sh, docs/how-to/assets/krustlet-service-account.yaml, docs/how-to/assets/krustlet.service, docs/how-to/kind.md, docs/how-to/minikube.md, src/krustlet-wascc.rs, src/krustlet-wasi.rs
This also stubs out the rest of this documentation and includes a tiny
bug fix to make sure flags load before the kubeconfig in binaries.
Closes #88
=> feat(docs): Adds how-to guides with complete AKS guide

demos/wasi/hello-world-assemblyscript/README.md, demos/wasi/hello-world-c/README.md, demos/wasi/hello-world-rust/README.md
Because the examples in the WASI demo are pre-built and ready to go, I felt that should be the first thing users can try out. If they want to recreate the example for themselves, they can do so by following the instructions.
=> docs(demos): shift around WASI demo docs

CONTRIBUTING.md, README.md, demos/wasi/hello-world-assemblyscript/README.md, demos/wasi/hello-world-c/README.md, demos/wasi/hello-world-rust/README.md, docs/README.md, docs/community/code-of-conduct.md, docs/community/developers.md, docs/howto/README.md, docs/howto/krustlet-on-aks.md, docs/howto/kubernetes-on-aks.md, docs/howto/kubernetes-on-kind.md, docs/intro/install.md, docs/intro/quickstart.md, docs/intro/readnext.md, docs/intro/tutorial01.md, docs/intro/tutorial02.md, docs/intro/tutorial03.md, docs/topics/architecture.md, docs/topics/providers.md
120 characters is too long for many editor UIs to handle, and 80 seems a little on the low side for writing documentation. 100 looks just right.
=> ref(docs): word wrap at 100 characters

crates/kubelet/src/handle.rs, crates/kubelet/src/lib.rs, crates/wasi-provider/src/lib.rs, crates/wasi-provider/src/wasi_runtime.rs
This adds a new `Stop` trait that can be implemented per provider while still preserving
all the pod and container management goodness of the handles. Yes, there are
now 2 generic types on the handle structs, but after discussing it with @rylev
we are ok with this as a middleground for now. This should enable any provider to
take advantage of these handles.
Please note that I removed the test for the wasi runtime because with the new
implementation, we can't wait on things to complete right now. Also, the same
functionality is being covered in the e2e tests
=> ref(handle): Moves handle to kubelet crate and makes it fully generic

Cargo.lock, Cargo.toml, crates/kubelet/src/handle.rs, crates/oci-distribution/Cargo.toml, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/lib.rs, crates/wasi-provider/src/wasi_runtime.rs
* Update tokio
* Rearrange generics in `RuntimeHandle` and `PodHandle` so that the stopper is listed before the logs reader since the former is arguably more important than the latter.
* Remove `BufReader` from RuntimeHandle since we're doing large and relatively infrequent reads which is the opposite of when `BufReader` works well. Additionally, seeking the inner reader of the `BufReader` does not fully work as the `BufReader` still has contents in its buffer potentially. 
* Fix docs links. We were using `crate::TYPE` links for items that were not available at the top level of the crate so the links were broken.
=> Small cleanup

README.md, crates/kubelet/src/kubelet.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/node.rs, crates/kubelet/src/provider.rs, crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs, demos/wasi/hello-world-assemblyscript/k8s.yaml, demos/wasi/hello-world-c/k8s.yaml, demos/wasi/hello-world-rust/k8s.yaml, docs/intro/tutorial03.md, examples/greet-wascc.yaml, examples/greet-wasi.yaml, justfile, tests/integration_tests.rs
This change forces pods to add a toleration for the specified architecture
before scheduling. Other normal pods were getting scheduled to the attached
krustlet nodes and ever starting before this.
I also found that we were listing _all_ pods instead of pods scoped to the
node, so now the informer has a field selector to only get pods that are
assigned to the node.
With this change, we no longer have a need for the `can_schedule` method, so
it has been removed from the provider trait
NOTE: I have also included a bugfix for getting nodes to go back to ready
on restart. It is hacky, but sufficient for now
Closes #126
=> fix(*): Adds node tainting to control pod scheduling

docs/intro/install.md, docs/intro/quickstart.md
The docs currently lead new users down a path of downloading Rust and
a bunch of other tools, which they may not be interested in doing immediately.
This adds some clarification that directs users to the demos if they
just want to get started with running something on their new Krustlet node
=> docs(intro): Clarify how to get started

docs/howto/README.md, docs/howto/krustlet-on-kubernetes-with-inlets.md
These instructions are agnostic of the distribution so will
work with AKS, EKS, GKE, Minikube, KinD, k3s, DOKS, you name it.
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
How has this been tested?
=> Add instructions for any Kubernetes cluster

docs/howto/assets/eks/.gitignore, docs/howto/assets/eks/Makefile, docs/howto/assets/eks/eks-worker-al2.json, docs/howto/assets/eks/files/bootstrap.sh, docs/howto/assets/eks/files/krustlet.service, docs/howto/assets/eks/scripts/install-worker.sh, docs/howto/assets/eks/scripts/validate.sh, docs/howto/krustlet-on-eks.md
This PR adds scripts for building a Krustlet-based AMI and defining an EKS
cluster using Krustet.
It also provides a walkthrough of how to get Krustlet running on EKS.
Closes #130.
=> Add a HOWTO for running Krustlet on EKS.

crates/oci-distribution/src/client.rs
I'm trying to run a pod with an image on my own registry, but when the pod was created, I saw that in my registry's log: `OCI manifest found, but accept header does not support OCI manifests"}]}`
Appended "application/vnd.oci.image.manifest.v1+json" in the `accept` header, it works now.
=> fixed: now krustlet can pull wasm image from standard registry

Cargo.lock, crates/kubelet/Cargo.toml, crates/kubelet/src/config.rs
If no password is provided as a flag, prompt for one. Passewords are mandatory for PFX bundles, so there's no need to wrap this in an `Option`.
closes #141 
=> feat(config): prompt for --pfx-password

Cargo.lock
This bumps everything to the latest version supported by our constraints.
Particularly, this solves a panic issue with wascc-host that was solved in
the latest patch release
=> chore(*): Bump dependency versions

crates/kubelet/src/config.rs, crates/kubelet/src/node.rs, docs/howto/assets/eks/files/bootstrap.sh, docs/howto/assets/eks/files/krustlet.service, docs/howto/krustlet-on-eks.md
Add `--node-labels` to the command line option which appends extra
labels when registering a Krustlet node.
Disclaimer: My Rust skill is rusty and my code may not be idiomatic Rust code :-).
This fixes https://github.com/deislabs/krustlet/issues/184
=> Allow specifying labels

CONTRIBUTING.md
=> fix(CONTRIBUTING): remove duplicate reference to the Code of Conduct

docs/howto/assets/eks/Makefile, docs/howto/assets/eks/eks-worker-al2.json, docs/howto/assets/eks/scripts/install-worker.sh, docs/howto/krustlet-on-eks.md
Allow passing in `KRUSTLET_VERSION` & `KRUSTLET_SRC` when building Krustlet AMI with packer. This allows building an AMI for changes in a forked repo.
=> Allow building Krustlet from a different repo for EKS

crates/kubelet/src/kubelet.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/queue.rs, crates/kubelet/src/server.rs
Our old event handling method locked the provider for any pod until event
handling was complete, essentially limiting us to one action at a time.
This introduces a new queuing method that creates a per pod queue that
only handles the latest sent event.
=> fix(kubelet): Adds per pod queuing

.github/workflows/release.yml
The bash substitution is not portable and will not work on macOS runners (old version of bash?). Using `tr` is portable and should work across both POSIX systems.
=> posix-compatible lowercasing

crates/kubelet/src/config.rs, crates/kubelet/src/node.rs
Update node-labels help to match original [issue](https://github.com/deislabs/krustlet/issues/184) .  Added method that aggregates static, dynamic, and user defined node labels.  User defined node labels are constrained per the man page rules.
=> add node label constraints per man page

crates/kubelet/src/volumes.rs
I found a tiny typo in error message.
=> Fix tiny typo in error message

docs/howto/krustlet-on-eks.md, docs/howto/krustlet-on-kind.md, docs/howto/krustlet-on-wsl2.md, docs/howto/kubernetes-on-eks.md, docs/howto/kubernetes-on-minikube.md
The guide for running Krustlet on EKS describes how to spin up an EKS cluster, so this guide can be removed.
I also word-wrapped everything to 100 characters in a separate commit.
=> chore(howto): remove empty HOWTO guide for EKS

.vscode/settings.json
In the default Ubuntu configuration, VS Code displays a "too many files to watch" warning when opening the Krustlet directory.  Rather than updating a global setting that could consume a lot of memory, we can tell VS Code not to watch the `target` directory.
=> Don't watch files under ./target in VS Code

crates/kubelet/src/config.rs, crates/kubelet/src/kubelet.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/node.rs, crates/kubelet/src/provider.rs, crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs
Not sure if this is something you all are interested in, in particular it allows for non-wasm providers .
* (unrelated) Make `stream_logs` available to providers that don't use Pod/RuntimeHandle.
* Create builder pattern for constructing node definitions.
* Implement basic defaults for node definition.
* Populate builder with calculated values and values from config.
* Give Provider an opportunity to edit the node definition.
* Move wasm-specific taint/architecture to example providers.
=> Allow Provider to Edit Node Definition.

.github/workflows/build.yml, crates/kubelet/src/config.rs, docs/howto/assets/eks/files/bootstrap.sh, docs/howto/assets/eks/files/krustlet.service, docs/howto/assets/krustlet.service, docs/howto/krustlet-on-aks.md, docs/howto/krustlet-on-gke.md, docs/howto/krustlet-on-kind.md, docs/howto/krustlet-on-microk8s.md, docs/howto/krustlet-on-minikube.md, docs/howto/krustlet-on-wsl2.md, docs/howto/krustlet-with-inlets.md, justfile
A recent change switched things back to a separate cert and key. However
the `just bootstrap` target was not updated to reflect this. I also noticed
some inconsistencies with how we were setting the default file path for
the cert and key and corrected those.
This also updates all of the docs to reflect the change
=> fix(*): Updates justfile and config to work with new cert setup

Cargo.lock, crates/kubelet/Cargo.toml, crates/kubelet/src/config.rs, crates/kubelet/src/kubelet.rs, crates/kubelet/src/node.rs, crates/kubelet/src/pod.rs
I wanted to invite comments on what I have been working on:
* Catch sigterm and certain errors and trigger graceful shutdown.
* Graceful shutdown cordons node and evicts pods, before deregistering it with the apiserver.
* Refactor kubelet futures for readability.
* Rework the combinators used for kubelet futures to enable graceful error handling.
This seems to do a good job of allowing Kubernetes to reschedule pods, rather than leaving zombie pods, and it gives the provider an opportunity to properly clean up pod resources as they are deleted. I'm not totally sure if all of this is desired behavior so I wanted to get some feedback before continuing.
=> Graceful shutdown. 

.cargo/config
This is necessary for compiling krustlet-wasi and krustlet-wascc for 64-bit ARM devices (and eventually 32-bit ARM as well, though that is currently not supported).
TODO:
=> add cross-compile target config

.github/workflows/build.yml
This PR updates `@engineerd/setup-kind` to [the latest version](https://github.com/engineerd/setup-kind/releases/tag/v0.4.0) because of a change in the underlying worker infrastructure.
It also updates the `@engineerd/configurator` action to [the latest version](https://github.com/engineerd/configurator/releases/tag/v0.0.2).
=> Update setup-kind GitHub Action

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/kubelet/src/server.rs, crates/oci-distribution/Cargo.toml, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml
This makes it so we don't have to compile against specific versions
of openssl and might make Windows easier.
This also updates our kube and openapi dependencies
Closes #247
=> feat(*): Update dependencies to use rustls instead of openssl

Cargo.lock, crates/kubelet/Cargo.toml, crates/kubelet/src/config.rs, demos/wascc/fileserver/Cargo.lock, docs/topics/README.md, docs/topics/configuration.md, src/krustlet-wascc.rs, src/krustlet-wasi.rs, tests/integration_tests.rs
Fixes #202.
With this PR, the kubelet configuration can be read from a config file as well as from the CLI.  If an option is specified in both the CLI and the config file, the CLI takes precedence.
The initial version of this PR is rather prototype-y and the following things remain to be refined:
* ~Agree better names for the config file keys~ I have now agreed these. With myself.
* ~Agree default config file path~ Ditto
* How to override default config file path e.g. environment variable and/or command line flag
* Default config file should probably be YAML rather than JSON though we hates them all precious
* ~Improve error messages for invalid config file entries~ They're not going to win any prizes but they're less worse than they were I think
* Agree on-error behaviour - currently …
=> Read settings from config file

.github/workflows/release.yml
This way the `crates` job won't start until krustlet is built and uploaded to Azure.
addresses the first point in #263
=> fix(ci): add dependency on publish action

docs/howto/assets/bootstrap.sh, docs/howto/bootstrapping.md, justfile
As these are hack scripts to help spin up a development environment, we should lean towards usability over security.
WSL does not have enough entropy available to generate a random seed with /dev/random.
Using /dev/urandom is less cryptographically secure, but it enables users on WSL to utilize the hack script.
closes #276
=> fix(docs): use /dev/urandom for generating token secrets

.github/workflows/build.yml, crates/kubelet/src/bootstrapping.rs, crates/kubelet/src/config.rs, crates/kubelet/src/node.rs, crates/kubelet/src/server.rs, justfile
This updates the environment variable setting for the TLS flags and
changes those flag names to be simpler.
Please note, I will be updating the docs on this in #289
=> chore(*): Change the tls flag name to be less verbose

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml, justfile
We were missing some feature enablement on the reqwest dependency.
I also took the time to update us to the latest version of the `kube`
crate. This has been tested against a "real" (AKS in this instance)
Kubernetes cluster and works great. There are still problems with
running it with minikube, kind, and any other cluster that doesn't
have an actual FQDN. This is an upstream issue that we'll need to
tackle separately
This is part of the work for #20
=> fix(*): Fixes Rustls builds

demos/wasi/simpleserver/README.md, docs/howto/bootstrapping.md, docs/howto/krustlet-on-kind.md
I'm still concerned that it isn't very clear. The bootstrapping procedure appears to be duplicated in several places (each Kubernetes flavor). Might be better to point them all at the one Bootstrapping README.
=> Fix typo and Bootstrapping clarification

crates/oci-distribution/src/client.rs
According to the [Docker registry documentation](https://docs.docker.com/registry/spec/auth/token/#requesting-a-token),
`token` is the preferred field and `access_token` is used for OAuth 2
compatibility.
This commit changes the expected auth response to be `token` with an alias of
`access_token` to support both.
=> Use `token` for image registry auth. 

.github/workflows/release.yml
closes #263 by allowing the job to succeed when `cargo publish` fails to release a package.
=> continue on error when `cargo publish` fails

justfile
This is sort of an opinion piece, but I feel like every time I run `just`, I expect it to run similar to `make`: it should only compile the project instead of running something.
This way, the instructions could be simplified to `just && just install` to install the wascc and wasi providers - assuming we had an `install` target.
=> switch default target to `build`

Cargo.lock, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/wasi_runtime.rs, tests/integration_tests.rs
There is an issue where if a WASM module fails (for example, with Rust source, if `main` returns an `Err`), it takes down the entire `krustlet-wasi` process.  This fixes that issue: now, if a module fails, the pod will terminate with a nonzero exit code (the exact value will depend on the WASM language binding but in Rust it appears to default to 1).
NOTE: The bad behaviour was down to an issue in wasmtime 0.16: a Rust error return was compiled into a call to a runtime-provided `proc_exit` function, which simply called the Rust stdlib function `std::process::exit`.  This was fixed in 0.18 - `proc_exit` now raises a trap, which the wasmtime CLI handles by exiting, but which we simply treat as a failure.  However, we can't use 0.18 because it doesn't allow us to redirect stdout and stderr …
=> Fix kubelet exit on module failure

crates/kubelet/src/container/mod.rs, crates/kubelet/src/kubelet.rs, crates/kubelet/src/node/mod.rs, crates/kubelet/src/pod/mod.rs, crates/kubelet/src/provider/mod.rs, crates/kubelet/src/store/mod.rs, crates/kubelet/src/store/oci/file.rs, crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs
Basically, mirror Pod API behavior for Container, wrapping KubeContainer and providing nice accessor methods. 
As a start, I moved Image and PullPolicy parsing into the container module.
=> Implement an API similar to Pod for KubeContainer

Cargo.lock, crates/wascc-provider/Cargo.toml, crates/wascc-provider/src/lib.rs, demos/wascc/fileserver/README.md, demos/wascc/fileserver/k8s.yaml, demos/wascc/greet/README.md, demos/wascc/greet/greet-wascc.yaml, demos/wascc/hello-world-assemblyscript/README.md, demos/wascc/hello-world-assemblyscript/k8s.yaml, demos/wascc/uppercase/README.md, demos/wascc/uppercase/uppercase-wascc.yaml, tests/integration_tests.rs
Fixes #288 
When multiple waSCC demos are running on the same port (containerPort or hostPort), to avoid thread panics, automatically maps the ports following these behaviors: 
1. If containerPort is specified and hostPort is not, then automatically assign a port number
2. If hostPort is specified (whether or not containerPort is specified), then try to assign that port number. If it is taken, the pod will error (the pod fails)
=> Add automatic port mapping for waSCC demos

crates/kubelet/src/container/handle.rs, crates/kubelet/src/node/mod.rs, crates/kubelet/src/pod/handle.rs, crates/kubelet/src/pod/mod.rs, crates/kubelet/src/pod/status.rs, crates/kubelet/src/store/mod.rs, crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs, tests/integration_tests.rs, tests/pod_builder.rs
Fixes #25 
**NOTES:**
* This first drop _only supports init containers in the WASI provider._  #25 requires them for all runtimes.
* ~waSCC will be harder to test because it doesn't allow us to pass command line args.  We can address this by improving the wasmerciser to accept commands via an environment variable as well as the command line.~ _EV support is now implemented_
* ~This will not currently pass CI because the integrations tests use the wasmerciser (to write a file in the init container and then read it back in the main container).  I've checked the tests pass on my machine by using a hacked store that can load from local `.wasm` files, but they won't work yet with the real OCI store.~
=> Support init containers

docs/howto/krustlet-on-microk8s.md
Updating the MicroK8s howto docs to make the users aware of the `--enable-bootstrap-token-auth`. If it's not enabled, the bootstrap authentication process fails with a 401 Unauthorized.
=> Update microk8s howto docs prerequisites

crates/kubelet/src/config.rs, crates/kubelet/src/node/mod.rs, crates/kubelet/src/pod/handle.rs, crates/kubelet/src/pod/mod.rs, crates/kubelet/src/store/composite/mod.rs, crates/kubelet/src/store/fs/mod.rs, crates/kubelet/src/store/mod.rs, crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs, docs/topics/configuration.md, src/krustlet-wascc.rs, src/krustlet-wasi.rs
During the dev-test cycle it can be useful to load modules that have been built locally but not pushed to a registry.  This PR supports this via a new `--allow-local-modules=true` command line flag (also available via environment variable or config file).  If `--allow-local-modules` is `true`, references of the form `fs/<path>` are loaded directly from the file system instead of from a registry.  For example:
* `fs//wasm/mymodule.wasm` - loads from absolute path `/wasm/mymodule.wasm`
* `fs/./out/mymodule.wasm` or `fs/out/mymodule.wasm` - loads from path `out/mymodule.wasm`, relative to the working directory of the kubelet process
As it is the custom kubelet (e.g. `krustlet-wasi`) which constructs the module store, it is up to that code to honour the `--allow-local-modules` flag. …
=> Option to load modules from local filesystem

Cargo.lock, crates/wasi-provider/Cargo.toml, demos/wascc/fileserver/k8s.yaml, demos/wascc/greet/greet-wascc.yaml, demos/wascc/hello-world-assemblyscript/k8s.yaml, demos/wascc/uppercase/uppercase-wascc.yaml
This should contain all of the changes we had in the pinned commit as
well. Also, I realized when doing a sanity check/test, that we should
have configured hostPorts in our wascc examples so the instructions
for the demos are correct
=> chore(*): Bumps wasi crates to 0.19

Cargo.toml, tests/assert.rs, tests/integration_tests.rs, tests/pod_builder.rs, tests/pod_setup.rs, tests/test_resource_manager.rs
This PR breaks up the single WASI megatest into a bunch of more granular test functions, currently one per pod used in the testing.  The tests are now able to run in parallel and are kept separate through namespaces.  The pattern for creating new tests is intended to be clear and to require minimal programmer effort, so that we will hopefully be inclined to write new tests for new things and not bolt things onto existing tests out of laziness!
I also moved a bunch of stuff out of the main test file into helper files - some of this, such as the `TestResourceManager` is behavioural, but other parts are just moving things to make the main file a bit more navigable.
=> Modularise WASI integration tests

crates/kubelet/src/bootstrapping/mod.rs, src/krustlet-wascc.rs, src/krustlet-wasi.rs
This adds a notification to the bootstrap process to inform the user when they need to approve a CSR.  It serves two purposes:
1. Currently if you do `bootstrap.sh` and then, say, `just run-wasi`, the kubelet just sits there but all your tests fail because it's waiting on TLS cert approval.  Now the user will have a visual prompt of what they need to do.
2. In preparation for #318, it provides a point in the output where a test harness can know that the CSR is ready, and can extract the CSR name in order to approve it.
Note that the actual interaction is NOT provided by the `kubelet` crate, either by logging macros or by `println!`.  This is because we cannot control the log level on the `kubelet` crate, and we do not want to use `println!` in the crate because it could in principle be …
=> Notify user if they need to approve a bootstrap CSR

crates/wascc-provider/src/lib.rs
This fixes an issue where capabilities that the actor did not add to its claim are being added, causing a runtime error. We should only be binding capabilities that the actor requested.
closes #239
=> bind capabilities if actor has it in its claims

.github/workflows/release.yml
A recent bug was introduced to the azure CLI preventing `az storage blob upload-batch` from working. In the meantime, a hotfix has been provided to the HEAD of azure-blob-storage-upload reverting back to azure-cli v2.9.1
The `sync` flag was also introduced since v1.0.0, which is enabled by default. sync must be disabled to preserve files currently present in the storage account.
=> downgrade to azure-cli 2.9.1

.github/workflows/release.yml
often, a new publish of the kubelet crate may need to wait until the new version of oci-distribution is available.
closes #341
=> fix(release): sleep for 60 seconds before publishing kubelet

crates/oci-distribution/src/client.rs
We have dead code warnings for the `oci_distribution::Client::version` function.  It's not clear whether it was intended to be public, or simply fell out of use.  As there are tests for it, I'm guessing the former.  Reviewers, if you think it's truly dead code, comment and I'll do it that way instead *grin*.
=> OCI client version function was showing as dead code

Cargo.lock, Cargo.toml, docs/community/developers.md, justfile, tests/oneclick/src/main.rs
Addresses #318.
This PR adds a new binary which, when run, does the following:
* Builds the WASI and WASCC kubelets
* Checks if bootstrapped certificates exist; if not, cleans up what does exist and runs the bootstrap script
* Launches both kubelets
* If bootstrapping, monitors both kubelets for the certificate approval message, and approves the certificate
* Runs the integration tests and waits for them to complete
* If the tests fail, captures the kubectl stdout and stderr to files, and prints the test failure details
* Terminates the running kubelets
There is still a lot that could be improved about this, e.g. stream test results as they arrive, send the logs to a better place than the current directory, etc.  But I think it's a useful first step.
Because we can now build and test on …
=> Self-contained integration tester

.github/workflows/release.yml
I noticed a few things that went awry with the windows build:
- the .exe file extension was not present for the executables
- setting the release version ran under powershell instead of bash
- the architecture used was "msvc", but the download link expected the architecture "amd64".
closes #346.
=> fix Windows build

crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs, demos/wascc/fileserver/k8s.yaml, demos/wascc/greet/greet-wascc.yaml, demos/wascc/hello-world-assemblyscript/k8s.yaml, demos/wascc/uppercase/uppercase-wascc.yaml, demos/wasi/greet/greet-wasi.yaml, demos/wasi/hello-world-assemblyscript/k8s.yaml, demos/wasi/hello-world-c/k8s.yaml, demos/wasi/hello-world-rust/k8s.yaml, demos/wasi/simpleserver/simpleserver.yaml, docs/howto/krustlet-on-gke.md, docs/howto/wasm.md, docs/intro/tutorial03.md, tests/integration_tests.rs, tests/pod_builder.rs
Please note that this is a breaking change that should be called out
in the release notes. This updates all documentation and examples
to use the new taint name.
Closes #334
=> ref(*): Renames node taint to `kubernetes.io/arch`

Cargo.lock, crates/kubelet/Cargo.toml, crates/kubelet/src/kubelet.rs, crates/kubelet/src/node/mod.rs, crates/kubelet/src/pod/mod.rs, crates/kubelet/src/pod/queue.rs, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml
Please note that this introduces a bunch of deprecation warnings. This
will only be temporary. Once the state machine work is done, we will
remove the deprecated functions and replace with the `kube-runtime`
crate.
Closes #170 by way of a transitive dependency update
=> chore(*): Update kube to 0.40

docs/community/developers.md
This can be done in one command instead of running each command and waiting for it to finish before progressing to the next one.
Also fix some incorrect/missing Markdown syntax highlighting annotations.
=> Tidy up WSL2 setup commands

crates/kubelet/src/config.rs, crates/kubelet/src/config_interpreter.rs, crates/kubelet/src/node/mod.rs
Replace some artisanal values with constants from the standard library.
➕ Drop two `Self` annotations that clippy bugged me about.
=> Use IP constants instead of parsing at runtime

crates/kubelet/src/node/mod.rs, demos/wascc/fileserver/k8s.yaml, demos/wascc/greet/greet-wascc.yaml, demos/wascc/uppercase/uppercase-wascc.yaml
This was causing failures when trying to register the node. See the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md#proposal) for more information
=> fix(kubelet): Removes node role label for compatibility with k8s 1.19

crates/kubelet/src/lib.rs, crates/kubelet/src/pod/mod.rs, crates/kubelet/src/secret/mod.rs, crates/kubelet/src/store/composite/mod.rs, crates/kubelet/src/store/fs/mod.rs, crates/kubelet/src/store/mod.rs, crates/kubelet/src/store/oci/client.rs, crates/kubelet/src/store/oci/file.rs, crates/oci-distribution/src/client.rs, crates/oci-distribution/src/lib.rs, crates/oci-distribution/src/secrets.rs, crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs
Fixes #257.
Do we have any thoughts on how to test it?  I can set up a private ACR registry, similar to `webassembly,azurecr.io`, and a SP with pull only permissions, but I'm a bit anxious about:
1. How do we keep track of/protect the registry so it doesn't accidentally get deleted in a tidy-up?
2. Posting a password, even a read-only one, in a public repo.
In the meantime I've tested it privately, and it seems okay though I'm worried that it seems to make the integration test flakes worse (and increasing the timeouts doesn't seem to help).
=> Image pull secrets

src/krustlet-wascc.rs, src/krustlet-wasi.rs
supersedes #378 by increasing the type length limit to work around an issue in the Rust compiler with nested closure wrappers (see https://github.com/rust-lang/rust/issues/54540 and https://github.com/rust-lang/rust/issues/75992 for more information).
=> increase type length limit

tests/oneclick/src/main.rs
Previously, if a kubelet crashed during integration testing, you got a bunch of cryptic errors about "unable to fetch terminating state" and "can't retrieve logs."  This PR provides additional diagnostics in `just test-e2e-standalone` if someone - some Moriarty of Montreal, say, or some Charles Augustus Milverton of Manitoba, some Irene Adler of Alberta - does something that causes this to happen.
=> Warn if a kubelet crashes during integration testing

Cargo.toml, docs/community/developers.md, tests/podsmiter/src/main.rs
Fixes #366.  If integration tests fail in a way that leaves pods stuck in `Terminating`, you can `cargo run --bin podsmiter` to delete the pods, after which the namespaces will clear up automatically.
(As an alternative to a post-test cleanup script, we could modify the integration tests to force-delete the pods in its cleanup; I haven't done that because I thought there might be cases where we'd want to look at stuck ones before blowing them away; but it would certainly be easier if we didn't care about that.  Having a script also allows cleanup if the test process fails to clean up for whatever reason.)
=> The podsmiter

.github/workflows/ci.yml
Currently E2E tests on PRs are failing because... well, okay, lots of reasons right now, but a fundamental one is that PRs don't have access to the secret needed to run the image pull secrets test, and there's no way we know of to grant that access to 'approved' PRs.
This PR therefore separates the `build.yml` workflow that does public E2E tests and can run on every PR and a new `ci.yml` workflow that also runs tests that use secrets, and runs only after a PR merges to the main branch.
Ironically, I can't see a way to test the on-merge-to-master workflow without, er, merging it to master.
**REVIEWERS:** It's a bit awful duplicating the bodies of the workflows, but I couldn't see a way to conditionally set environment variables depending on the trigger, nor to pull out the bulk into a …
=> Run secrets tests only when secrets are available

crates/wascc-provider/src/states/starting.rs, crates/wascc-provider/src/states/terminated.rs, crates/wascc-provider/src/states/volume_mount.rs, crates/wasi-provider/src/states/terminated.rs, crates/wasi-provider/src/states/volume_mount.rs
There are a few places in the WASCC provider where it unwraps an error (causing a panic) or returns an error from a state runner (causing the run loop to terminate).  These should all or mostly transition the pod to the Error state instead.  This PR does that.
The work here suggests a possible change to the design of the state `next` function: instead of returning a `Result<Transition, ...>` it should perhaps strictly return a `Transition`, thus preventing maintainers lazily letting an unhandled error sneak up to the run loop.  If a provider needs an "everything has turned to custard and we just want to die and never come back" behaviour, then we could add a `Transition::Fatal` member to the Transition enum, which the run loop could check for.  This would force authors to specifically …
=> WASCC pods should transition to error state instead of kerploding

crates/kubelet/src/kubelet.rs, crates/kubelet/src/node/mod.rs, crates/kubelet/src/pod/mod.rs, crates/kubelet/src/pod/queue.rs, crates/wascc-provider/src/states/registered.rs
Pod is a wrapper struct around k8s_openapi's Pod, but many callers use `Pod::new(pod)` instead of `Pod::from(pod)`.
This commit removes the constructor, forcing the caller to rely on calling `::from` to instantiate a new Pod. This also allows a Pod to expose more fields in the future (such as a pod's current state).
conflicts with #344, which should be merged prior to this PR to prevent another rebase.
=> ref(pod): switch from tuple to regular struct; use Pod::from

crates/kubelet/src/container/mod.rs, crates/kubelet/src/store/oci/file.rs, crates/oci-distribution/src/reference.rs
This is a starting number of changes to the reference parser. With these changes, the following occurs:
- we have access to concrete string types after parsing
- reference now returns its own custom types. This way, the errors reported from reference.rs are known
- an error is raised if the length exceeds the name total max length
Follow-up PRs will start refactoring the parser to match the one in docker/distribution. That way we can handle cases like #397.
=> ref(reference): add custom error types to match docker/distribution

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/kubelet/src/bootstrapping/mod.rs, crates/kubelet/src/config.rs, crates/kubelet/src/kubelet.rs, crates/kubelet/src/pod/handle.rs, crates/kubelet/src/pod/mod.rs, crates/kubelet/src/pod/queue.rs, crates/kubelet/src/store/oci/file.rs, crates/oci-distribution/src/client.rs, crates/wascc-provider/Cargo.toml, crates/wascc-provider/src/lib.rs, crates/wascc-provider/src/states/starting.rs, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/lib.rs, crates/wasi-provider/src/states/initializing.rs, crates/wasi-provider/src/states/starting.rs, tests/integration_tests.rs, tests/pod_setup.rs, tests/podsmiter/src/main.rs, tests/test_resource_manager.rs
This replaces all uses of the `Informer` with the new `watcher` type from the `kube_runtime` crate. I also fixed a bunch of clippy lints I found along the way
This also contains a refactor around pod keys by introducing the new `PodKey` type. This serves 2 main purposes. The first is it makes it clear that we are using key for a pod rather than it just being a `String`. The second is that instead of it being an arbitrary string, it now has separate fields that define the key. Arbitrary strings and separators (even with an alias type) can come back to bite, so this makes it a concrete type with separate fields. As part of this, I have deprecated, but not removed, the old pod key methods
=> ref(*): Removes use of deprecated `Informer` from the `kube` crate

Cargo.lock, Cargo.toml, crates/wascc-logging/Cargo.toml, crates/wascc-logging/src/lib.rs, crates/wascc-provider/Cargo.toml, crates/wascc-provider/src/lib.rs
This is just a general hygiene PR to update all dependencies possible to their latest version. There were small code changes to update with the new APIs from some libraries. I was not able to update `hyperx` because our www-authenticate crate depends on a trait from the older version.
I also can't update wasmtime to 0.20 yet due to wascc requiring 0.19. We'll have to stick with it until we split out the crates or wascc upgrades
=> chore(*): Bumps all deps to the latest version

.github/workflows/release.yml
release builds are failing because the macOS runners uses an older version of Rust. Adding the same hack from the build workflow should resolve the issue.
=> update rust and install rustfmt/clippy on macOS

crates/wascc-provider/src/lib.rs, crates/wascc-provider/src/states/starting.rs
Prior versions only passed a shortlist of known configuration to each capability. This PR passes the entire environment variable tree to each waSCC capabililty.
This effectively does nothing at the moment, but if we are to implement a way for users to provide their own capability providers, then they can populate those capabilities with their pod's environment variables.
closes #338
=> pass all environment variables to each capability

.github/workflows/release.yml
`cargo build --release --target aarch64-unknown-linux-gnu` places the release assets under `target/aarch64-unknown-linux-gnu/release` rather than `target/release`.
=> fix target release directory for aarch64

crates/oci-distribution/src/reference.rs
=> References were formatted incorrectly on Windows

docs/howto/krustlet-on-wsl2.md
These flags are not referenced or utilized anywhere in the HOWTO guide, and are using the default values for these flags, so they are safe to remove from the flag list. It just confuses the reader.
ref: #447
=> remove unused flags

crates/kubelet/src/store/oci/client.rs, crates/oci-distribution/src/client.rs, crates/oci-distribution/src/manifest.rs
This will allow us to catch unsupported OCI manifests (like manifest lists) early on in the process before we attempt to parse that data as an OCI manifest.
We'll also exit out early on if the manifest layer content is empty. This is more of a theoretical test case (have you ever heard of a docker image without any layers?), but it's worth catching as an error case to prevent a case where a provider can receive an `ImageData` object with empty content.
=> implement more strict manifest checks

.github/workflows/release.yml
ref: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
=> migrate deprecated API calls to $GITHUB_ENV

.github/workflows/release.yml
Arguments need to use the context and expression syntax rather than bash variables.
https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#contexts
=> fix workflow syntax

crates/kubelet/src/store/oci/file.rs, crates/oci-distribution/Cargo.toml, crates/oci-distribution/src/client.rs, crates/oci-distribution/src/manifest.rs, crates/oci-distribution/src/secrets.rs
This PR includes the `push` function, which implements https://github.com/opencontainers/distribution-spec/blob/master/spec.md#push.
There are two tests that I didn't include as they involved a private registry and credentials:
- Pushing a wasm to a registry with Basic authentication [PASS]
- Pushing a non-wasm file (wascc provider archive) to a registry with Basic authentication [PASS]
I have also used a registry `oci.registry.local`, which I've pointed to a local unauthenticated docker registry, for my tests, and I'm open to modifying that depending on how this project aims to test this crate.
It involves a semver bump to `0.5.0` because the API for `auth` and `pull` changed to include the type of authentication, which is stored as the `RegistryOperation` enum.
Looking forward to your …
=> oci-distribution Push functionality

crates/oci-distribution/src/client.rs
This solves #469 It should be a no brainer.
Trying to request the image from Google Artifacts returns `Bearer realm="https://europe-west1-docker.pkg.dev/v2/token"` without the `service` field. The [Distribution Spec](https://github.com/opencontainers/distribution-spec/blob/master/spec.md) doesn't tell anything about authentication AFAIK.
I found about the service field in the [Docker Registry docs](https://docs.docker.com/registry/configuration/#silly), so it's probably not needed anymore in Artifacts?
=> Check if service field is provided by auth challenge

crates/oci-distribution/src/client.rs
I missed this nit when I was reviewing #474. Also contains a `Cargo.lock` update that happened when I built 
cc @bacongobbler
=> ref(oci): Fixes nit I missed in inital review

crates/kubelet/src/bootstrapping/mod.rs, crates/kubelet/src/node/mod.rs, crates/oci-distribution/src/client.rs, crates/oci-distribution/src/reference.rs, crates/wascc-provider/src/states/container/waiting.rs
Addresses new Clippy lints. 
Ignores one type of lint in two locations due to https://github.com/rust-lang/rust-clippy/issues/6559
=> Clippy 1.49.0

docs/howto/krustlet-on-microk8s.md
Reran this document after a hiatus.
+ II[U|R]C setting `KUBECONFIG=foo ./krustlet-... ---bootstrap-file=bar` uses `bar` to authenticate to the cluster so `foo` is redundant
+ Corrected a typo in the `Step 3: test`
+ Updated the `hello-world-wasi-rust` output to reflect current state
Now to review the GKE instructions ;-)
=> Updated|Corrected Microk8s instructions

crates/krator/src/lib.rs, crates/kubelet/src/container/state.rs, crates/kubelet/src/kubelet.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/pod/state.rs, crates/kubelet/src/provider/mod.rs, crates/kubelet/src/state.rs, crates/kubelet/src/state/common/mod.rs, crates/wascc-provider/src/states/container.rs, crates/wascc-provider/src/states/pod.rs, crates/wasi-provider/src/states/container.rs, crates/wasi-provider/src/states/pod.rs, tests/ui/state/cannot_construct_transition_next.rs, tests/ui/state/cannot_construct_transition_next.stderr, tests/ui/state/next_must_be_state.rs, tests/ui/state/require_same_object_state.rs, tests/ui/state/require_transition_to.rs, tests/ui/state/require_transition_to.stderr
We were planning to deprecate, but deprecation warnings don't seem to work for `pub use`. 
Branched off of #499 so that should probably merge first.
=> Remove Krator::state re-export

crates/krator/Cargo.toml
I put it there for testing and forgot to remove it. I also made sure it
was listed as a required feature for the moose example so people get a
nice error message if they don't pass the feature flag
=> fix(krator): Removes `derive` feature from default

Cargo.lock, crates/kubelet/Cargo.toml, crates/kubelet/proto/pluginregistration/v1/pluginregistration.proto, crates/kubelet/src/kubelet.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/plugin_watcher/mod.rs, crates/kubelet/src/provider/mod.rs, crates/kubelet/src/state/common/mod.rs, crates/kubelet/src/state/common/terminated.rs, crates/kubelet/src/state/common/volume_mount.rs, crates/kubelet/src/volume/configmap.rs, crates/kubelet/src/volume/hostpath.rs, crates/kubelet/src/volume/mod.rs, crates/kubelet/src/volume/persistentvolumeclaim.rs, crates/kubelet/src/volume/secret.rs, crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs, demos/wasi/hello-csi/README.md, demos/wasi/hello-csi/k8s.yaml, docs/howto/README.md, docs/howto/csi.md, docs/topics/README.md, docs/topics/csi.md, docs/topics/plugin_system.md, src/krustlet-wascc.rs, src/krustlet-wasi.rs
Adds support for mounting PersistentVolumeClaims to a Pod via the Container Storage Interface.
Closes #182
=> PVC mount support

Cargo.lock, Cargo.toml, contrib/azure/azuredeploy.json, contrib/azure/azuredeploy.parameters.json, crates/kubelet/Cargo.toml, crates/kubelet/src/container/handle.rs, crates/kubelet/src/kubelet.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/state/common/terminated.rs, crates/kubelet/src/volume/mod.rs, crates/kubelet/src/volume/persistentvolumeclaim.rs, crates/oci-distribution/Cargo.toml, crates/oci-distribution/src/client.rs, crates/wascc-provider/Cargo.toml, crates/wascc-provider/src/lib.rs, crates/wasi-provider/Cargo.toml, docs/intro/install.md, tests/assert.rs, tests/expectations.rs, tests/integration_tests.rs, tests/pod_builder.rs, tests/pod_setup.rs, tests/ui.rs
This also includes a bunch of fixes for clippy lints that had piled up (we had something like 15 or 20). So those are all fixed now
=> chore(*): Bumps docs and cargo for 0.6

Cargo.lock, crates/krator-derive/Cargo.toml, crates/krator-derive/src/lib.rs
The dev dependency on krator led to a circular dependency issue that prevented
publishing of the crate. These changes were actually published with krator 0.1
so we could unblock things.
=> fix(derive): Fixes circular dependency

docs/howto/assets/bootstrap.sh
On macOS 11.2, `LC_CTYPE=C` was not sufficient:
```
tr: Illegal byte sequence
tr: Illegal byte sequence
error: error validating "STDIN": error validating data: [unknown object type "nil" in Secret.stringData.token-id, unknown object type "nil" in Secret.stringData.token-secret]; if you choose to ignore these errors, turn validation off with --validate=false
```
I needed to set `LC_ALL=C`.
=> Use LC_ALL to set all locale categories

Cargo.lock, crates/krator/Cargo.toml, crates/krator/examples/assets/deploy.sh, crates/krator/examples/assets/invalid_moose.yaml, crates/krator/examples/assets/webhook.yaml, crates/krator/examples/moose.rs, crates/krator/src/admission.rs, crates/krator/src/lib.rs, crates/krator/src/operator.rs, crates/krator/src/runtime.rs, crates/kubelet/src/pod/mod.rs
This allows the Operator to validate, mutate, and/or reject incoming objects. This seems to be an uncommon pattern, but it makes a lot of sense to me that an Operator gets to validate the objects that it acts on. This is completely optional behind a feature flag (disabled for Krustlet). 
I've updated the moose example for (optionally, based on feature) testing this functionality, and to demonstrate provisioning certificates for mTLS and configuring Kubernetes to use the endpoint.
=> Krator support for Admission Webhook

crates/krator/src/operator.rs, crates/krator/src/runtime.rs, crates/kubelet/src/operator.rs, crates/kubelet/src/provider/mod.rs, crates/kubelet/src/state/common/terminated.rs, crates/wasi-provider/src/lib.rs
* Update Krustlet to use this hook to clean up volume mounts, rather
than `Terminated` state.
Closes #504
=> Introduce deregistration hook in Krator Operator

crates/krator/Cargo.toml
Missed this in the Tokio update since its an optional dependency.
=> Bump to Warp 0.3

crates/krator/src/state.rs
Unfortunately I trusted [these docs](https://docs.rs/kube/0.42.0/kube/api/struct.PatchParams.html#structfield.patch_strategy) when determining which patch strategy we were using before we updated to `kube` 0.48. 
It turns out that strategic patches are not supported for Custom Resources, and [looking at the code](https://docs.rs/kube/0.42.0/src/kube/api/params.rs.html#246) it turns out that a merge patch was the default.
=> Use merge for Krator status patch.

Cargo.lock, crates/kubelet/src/grpc_sock/unix/mod.rs
This is some follow up to comments in #480. I have one more to make once
I am on a Windows machine (#531). I also considered having the Krator `Manifest`
use a `WatchStream` wrapper, but that has several trait bounds that we don't need
so I chose not to use it.
This also contains some minor version bumps for things
=> chore(kubelet): Removes unneeded stream wrapper

Cargo.lock, crates/krator/Cargo.toml, crates/krator/src/manifest.rs, crates/krator/src/object.rs, crates/krator/src/operator.rs, crates/krator/src/runtime.rs, crates/kubelet/src/container/state.rs
Closes #536 
@thomastaylor312 I know you didn't want to add all of these trait constraints, but this feels like the most stable solution given the trouble we've had with this (presumably `WatchStream` will be kept up to date and reliable by the Tokio team). In practice, this only adds one new trait to `Operator::Manifest`: `Unpin`, and required no changes outside of Krator.
=> Use WatchStream for Manifest.

crates/kubelet/src/pod/status.rs
Closes #546 
I did not create helper functions like `make_status_with_conditions` or `make_status_with_containers_and_conditions` because the builder already provides a convenient way to create a status with whatever information is at hand.
=> Pod conditions added to the StatusBuilder in kubelet

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release.yml
After GitHub's automatic branch renaming, actions were not running on main. This should fix that.
=> Change master to main in Actions Config

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml
Dirs dependencd has been flagged as unmaintained in https://rustsec.org/advisories/RUSTSEC-2020-0053
Fixes #565
=> Update dirs dependency to use dirs-next instead

Cargo.lock, crates/kubelet/Cargo.toml, crates/kubelet/src/mio_uds_windows/stdnet/ext.rs, crates/kubelet/src/mio_uds_windows/stdnet/net.rs, crates/kubelet/src/mio_uds_windows/test/test_close_on_drop.rs, crates/kubelet/src/mio_uds_windows/test/test_double_register.rs, crates/kubelet/src/mio_uds_windows/test/test_echo_server.rs, crates/kubelet/src/mio_uds_windows/test/test_local_addr_ready.rs, crates/kubelet/src/mio_uds_windows/test/test_oneshot.rs, crates/kubelet/src/mio_uds_windows/test/test_register_deregister.rs, crates/kubelet/src/mio_uds_windows/test/test_register_multiple_event_loops.rs, crates/kubelet/src/mio_uds_windows/test/test_reregister_without_poll.rs, crates/kubelet/src/mio_uds_windows/test/test_smoke.rs, crates/kubelet/src/mio_uds_windows/test/test_uds.rs, crates/kubelet/src/mio_uds_windows/test/test_uds_level.rs, crates/kubelet/src/mio_uds_windows/test/test_write_then_drop.rs, crates/kubelet/src/volume/persistentvolumeclaim.rs
Removes the dependency on tempdir which has been flagged as unmaintained in RUSTSEC-2018-0017.
Uses the tempfile crate instead, which has been in the dependency tree anyway, as warp depends on it.
Calls to TempDir were replaced with their equivalent from the tempfile crate.
The [documentation](https://docs.rs/tempfile/3.2.0/tempfile/#resource-leaking) for tempfile states the following: 
> tempfile will (almost) never fail to cleanup temporary resources, but TempDir and NamedTempFile will if their destructors don't run. This is because tempfile relies on the OS to cleanup the underlying file, while TempDir and NamedTempFile rely on their destructors to do so.
Which to me sounds like calling .tempfile() should be the preferred way. However as far as I can tell this does not offer creating …
=> Replaces the dependency on tempdir with tempfile (RUSTSEC-2018-0017)

crates/krator/src/runtime.rs
=> Clean-up phase in krator fixed where a channel was closed prematurely

Cargo.lock, Cargo.toml, crates/krator/Cargo.toml, crates/kubelet/src/plugin_watcher/mod.rs, justfile
I discovered this bug when testing. If a CSI plugin fails to clean up
its socket file in the plugin directory, on restart kubelet will exit with
an error. This addresses that issue and does a little bit of minor upgrades
in the various project crates (because it was annoying me). Oh, and I
reenabled kubelet logging in the justfile
You can create a fake socket file in your plugins directory like so:
```
$ touch ~/.krustlet/plugins/foo.sock
```
With this PR, you should now just see an error message logged, but kubelet
will not exit
=> fix(plugin): Avoids early termination of kubelet on startup

crates/kubelet/src/kubelet.rs, crates/kubelet/src/provider/mod.rs, crates/wasi-provider/src/lib.rs
This is a very simple first attempt at allowing providers to implement custom shutdown behavior.
I tried to be as minimally invasive as possible for the time being. I pass the node name into the shutdown function because I don't think the provider ever has access to the _real_ node object in a proper fashion, but I may be mistaken.
The only way I could find was to take it from the builder in the [node()](https://github.com/deislabs/krustlet/blob/b50bc34c1eafb59b59bc3eff39f643a213bea98e/crates/kubelet/src/provider/mod.rs#L105) function, but that would mean relying on the implementation detail that the kubelet sets the name on the builder before and not after passing the builder to the provider.
We could make this much more complex if we wanted, some ideas I had along the way and just want …
=> Allow providers to implement custom shutdown behavior

Cargo.lock, crates/krator/Cargo.toml, crates/krator/examples/moose.rs, crates/krator/src/admission.rs, crates/krator/src/object.rs, crates/krator/src/operator.rs, crates/krator/src/runtime.rs, crates/krator/src/state.rs, justfile
This tries to fix deislabs/krustlet#573
The kube-derive macro now implements `kube::Resource` instead of
`k8s_openapi::Resource` and and `k8s_openapi::Metadata`.
I think these adjustments should be ok, `however: kube::Resource` does not
have the method `metadata_mut()` and I couldn't fix the `resync` method
@kflansburg
I added the compilation of the example app to the github actions
workflow so this kind of error get get caught early
=> [wip] Adjust code to changed kube_derive

crates/kubelet/src/volume/configmap.rs, crates/kubelet/src/volume/hostpath.rs, crates/kubelet/src/volume/mod.rs, crates/kubelet/src/volume/persistentvolumeclaim.rs, crates/kubelet/src/volume/secret.rs
This adds a new `Mountable` trait that any volume can implement. Things
are better than before but not perfect and I think further refactor of
how we store references to volumes should be done before we hit 1.0.
Closes #482
=> ref(volume): Adds new `Mountable` trait

crates/kubelet/src/operator.rs, crates/kubelet/src/pod/handle.rs, crates/kubelet/src/pod/mod.rs, crates/kubelet/src/state/common/mod.rs, crates/kubelet/src/state/common/volume_mount.rs, crates/kubelet/src/volume/configmap.rs, crates/kubelet/src/volume/hostpath.rs, crates/kubelet/src/volume/mod.rs, crates/kubelet/src/volume/persistentvolumeclaim.rs, crates/kubelet/src/volume/secret.rs, crates/wasi-provider/src/lib.rs, crates/wasi-provider/src/states/container/waiting.rs, crates/wasi-provider/src/states/pod.rs
This builds on #584 (well actually tears down the original idea, but
you get it) and makes volume management all handled by the same object.
This is a breaking change that removes the `Ref` type and replaces it
with a fully managed `VolumeRef` type. I am not entirely happy with having
the unmounting being handled in the async_drop stage, but it is good enough
for now. It wouldn't be a breaking change to make it a new state down the line
if we want to move it.
Closes #585
=> ref(volume): Streamlines how volumes are mounted and unmounted

crates/kubelet/src/config_interpreter.rs, crates/oci-distribution/src/client.rs
Allow users to provide a `reqwest::ClientBuilder` instance when the `oci-distribution::Client` is created.
This can be useful for users who want to fine tune the client used to access the remote registry. For example, to add a root certificate to be used when connecting to a registry secured with a self-signed certificate.
This is a quick prototype, what I don't like about this solution is:
* Break the API of `oci-distrubution::Client`. The PR fixes the broken code, but what about other users of this crate?
* Expose the `reqwest::ClientBuilder`. Disclaimer, I'm new to Rust, in Go I would propose to use instead an interface as parameter. In Rust I would say we could request a series of traits to be provided by the `ClientBuilder`, but this would require changes inside of …
=> oci-distribution: expose client builder

crates/oci-distribution/src/manifest.rs
Needed to be able to download Docker images.
=> oci-distribution: add IMAGE_DOCKER_LAYER_GZIP_MEDIA_TYPE

demos/wasi/wasmerciser/src/main.rs, demos/wasi/wasmerciser/src/syntax.rs
At the moment, the wasmerciser `write` instruction only accepts variables or literals.  So if you want to dump a file to stdout, you have to read it into a variable first, then write the variable to stdout.  This was okay for most early use cases, but it was a non-obvious limitation - too easy to write `write(file:/test.txt)to(stm:stdout)` and get a mystifying error.
This PR does two things:
1. Enables `file` or a `env` as sources in the `write` instruction
2. Improves parse errors for all instructions, e.g. by listing permitted options
NOTE: if this PR is accepted we will need to build and push a new wasmerciser image.  This is still a manual process per the readme.
=> Wasmerciser: allow writing files or EVs out directly

crates/oci-distribution/src/client.rs, crates/oci-distribution/src/lib.rs, crates/oci-distribution/src/reference.rs
Also add a new public helper to pull OciManifest and the config JSON blob referenced by an OciManifest and expose `ParseError` so that `Reference` can be used more freely outside of `oci_distribution`.
=> Expose pull_manifest in public API.

.github/workflows/build.yml, .gitignore, Cargo.lock, Cargo.toml, crates/wasi-provider/src/wasi_runtime.rs, justfile, src/krustlet-wasi.rs, tests/csi/README.md, tests/csi/mod.rs, tests/csi/rbac.yaml, tests/csi/setup.rs, tests/csi/socket_server.rs, tests/integration_tests.rs, tests/oneclick/src/main.rs, tests/pod_builder.rs, tests/podsmiter/src/main.rs, tests/test_resource_manager.rs
This PR adds e2e tests for the CSI code as part of our polishing for 1.0. Right now these tests only run on linux as some of the dependent components don't yet run on Mac. Also, the mock driver would need to use all of our ugly Windows socket code so we don't test it there either. Basically this is all a bit ugly, but it does exercise basic testing of the CSI components of the system. I also updated `podsmiter` to account for the new resources we are creating.
Closes #579
=> feat(tests): Adds e2e tests for CSI

crates/kubelet/Cargo.toml, crates/kubelet/src/lib.rs, crates/kubelet/src/volume/configmap.rs, crates/kubelet/src/volume/persistentvolumeclaim.rs, crates/kubelet/src/volume/secret.rs
@thomastaylor312 
i have added the steps to resolve #625 unmount issue in windows using [remove_dir_all](https://crates.io/crates/remove_dir_all) crate only for windows and unix family will continue to have std::fs implementation as usual.
I'm unable to test this completely as i don't have Windows pc, I'm on M1 mac and elapsed parallels trial already :(
Compilation and just windows test has been passed.
Please let me know you thoughts !!
=> to fix: #625 - Windows cannot cleanup volumes on unmount 

Cargo.lock, crates/kubelet/src/volume/persistentvolumeclaim.rs
While reviewing another PR I noticed that we were still using a `std::fs`
function in an `async` location. This switches it out for tokio, and also
ended up updating the lock file that didn't get caught on a previous PR
=> fix(volumes): Removes blocking fs call

contrib/azure/azuredeploy.parameters.json
1.18.10 is deprecated, so the demo fails by default right now.
=> Updated default aks version to 1.20.7

.github/workflows/build.yml, Cargo.lock, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/wasi_runtime.rs
This commit updates Wasmtime to v0.28 and simplifies the way modules are instantiated using the linker.
=> Update Wasmtime to v0.28

Cargo.toml, crates/kubelet/Cargo.toml, crates/oci-distribution/Cargo.toml
This will allow `cargo-deny` to run without issues.
The docs (https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) are also not entirely clear: "If a package is using a nonstandard license, then the license-file field may be specified in lieu of the license field."
I decided to leave `license-file` in.
=> Explicitly specify license in Cargo.toml

demos/wasi/greet/greet-wasi.yaml
it's missing the arch selector present on the other manifests, so it doesn't always hit Krustlet nodes
=> fix: node selector for greet demo

.github/workflows/lint.yml, .markdownlinkcheck.json, crates/kubelet/src/mio_uds_windows/README.md, demos/wasi/hello-world-assemblyscript/README.md, docs/howto/README.md, docs/howto/kubernetes-on-minikube.md, docs/intro/quickstart.md, justfile
digitaloceans trial site worked manually in my browser, but it didn't seem to like the crawler. Maybe a useragent issue of some kind?
=> fix(docs): dead links; add markdown link check

crates/kubelet/src/volume/mod.rs
We had an exported type that wasn't used anywhere, so I wanted to remove
it from the API. This breaking change has already been added to the 1.0
release notes
=> feat(volumes): Remove unused type

CONTRIBUTING.md, LICENSE, README.md, docs/community/code-of-conduct.md, docs/community/developers.md
Namely, this updates the copyright to "The Krustlet Authors" now that
things have been transferred to the CNCF. Also adds some clarification
around MSRV as the most recent updates to `kube` use a new feature only
available after 1.53
=> chore(*): Updates docs now that we are in CNCF

crates/wasi-provider/Cargo.toml
fixes #654 
Signed-off-by: Sönke Liebau <soenke.liebau@gmail.com>
=> Added license property to Cargo.toml to specify Apache License 2.0

crates/oci-distribution/src/errors.rs
OCI errors were updated to be even with [the spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#errors-2):
* ~~`TAG_INVALID` and `MANIFEST_UNVERIFIED` were removed from OCI spec: https://github.com/opencontainers/distribution-spec/pull/206~~
* `TOOMANYREQUESTS` was added
Tested on CentOS 8.2.2004 and KinD with Kubernetes v1.21.1.
After bootstrapping a krustlet-wasi node I received this error:
> Jul 17 18:02:33.250 ERROR kubelet::state::common::image_pull: error=error decoding response body: unknown variant `TOOMANYREQUESTS`, expected one of `BLOB_UNKNOWN`, `BLOB_UPLOAD_INVALID`, `BLOB_UPLOAD_UNKNOWN`, `DIGEST_INVALID`, `MANIFEST_BLOB_UNKNOWN`, `MANIFEST_INVALID`, `MANIFEST_UNKNOWN`, `MANIFEST_UNVERIFIED`, `NAME_INVALID`, `NAME_UNKNOWN`, `SIZE_INVALID`, …
=> Fix OCI errors

.github/workflows/build.yml
We had a workaround for forcing k8s 1.20 that we forgot to remove once
we added 1.21 support. This also updates the main e2e test to use the
latest kind (which will also default to 1.21)
=> chore(ci): Removes specific k8s 1.20 image

tests/integration_tests.rs, tests/pod_builder.rs
This removes the static lifetimes on the wasmerciser structs. This
_may_ have been interfering with the ability to use string variables,
but it also was too much of a constraint where an explicit lifetime
would work just fine. This should make it much more flexible to use
=> ref(tests): Removes static lifetimes

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/kubelet/src/grpc_sock/unix/mod.rs, crates/kubelet/src/grpc_sock/windows/mod.rs, crates/oci-distribution/Cargo.toml, deny.toml, tests/csi/socket_server.rs
This addresses all warnings and failures from `cargo deny` as a follow
up to #641. It streamlines the allowed licenses for now. There are currently
some warnings that will be fixed once https://github.com/kflansburg/k8s-csi/pull/2 is merged.
There are also 2 license warnings remaining. Both of them are from krator and
will be fixed once there is a new version published to crates.io.
=> chore(*): Address `cargo deny` failures

crates/oci-distribution/src/client.rs
I was unable to use the OCI client to fetch manifest from ECR. It looks like this was caused by two things:
1. ECR uses HTTP Basic Auth, and does not issue a challenge header.
2. ECR does not appear to include the Docker Content Digest header that the OCI client expects. 
This PR makes two changes:
1. If no challenged header is issued when we attempt to GET the repository in the `auth` method, but credentials were supplied, the supplied credentials are stored as basic auth credentials. This involved inserting a new enum, `RegistryTokenType` for storing either bearer tokens or basic auth credentials. Next, the `auth_headers` method has been changed to `apply_auth`, and takes ownership of the `RequestBuilder` to inject the headers and configure basic auth if necessary. It also accepts …
=> HTTP Basic Auth and missing digest header

crates/kubelet/src/bootstrapping/mod.rs
The `certificates.k8s.io/v1beta1` API version of `CertificateSigningRequest` is no longer served as of Kubernetes v1.22. The `certificates.k8s.io/v1` API version is used instead which is available since v1.19.
The requirements of the new API version were already met:
> Notable changes in certificates.k8s.io/v1:
> * For API clients requesting certificates:
>   * `spec.signerName` is now required (see known [Kubernetes signers](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers)), and requests for `kubernetes.io/legacy-unknown` are not allowed to be created via the `certificates.k8s.io/v1` API
>   * `spec.usages` is now required, may not contain duplicate values, and must only contain known usages
>
> see …
=> Make CSRs compatible with Kubernetes v1.22

Cargo.lock, crates/kubelet/src/state/common/resources.rs, crates/kubelet/src/volume/mod.rs, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/states/container/waiting.rs, crates/wasi-provider/src/states/pod.rs
Currently, the piping is not in place for mounts specified by device plugins to be set in Pods. Nor is there support for mounting a host path at a specific container path.
This adds a new type of `VolumeRef` called `DeviceVolume` for specifying mounting a host path volume at a specific container path, as requested by a device plugin. It also modifies the WASI provider to enable appending volumes during the `Resources` state.
=> Enable Device Plugin Volume Mounts

crates/kubelet/src/volume/mod.rs
This turns out to be trivial because the enum is never used exhaustively in core Krustlet code except in the context in which the compiler allows.
Closes #673
=> Switched VolumeRef to non_exhaustive

Cargo.lock, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/wasi_runtime.rs, deny.toml
This PR updates Wasmtime to v0.30 -- see https://rustsec.org/advisories/RUSTSEC-2021-0110.html
=> Update Wasmtime to v0.30

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/kubelet/src/bootstrapping/mod.rs, crates/kubelet/src/container/mod.rs, crates/kubelet/src/kubelet.rs, crates/kubelet/src/node/mod.rs, crates/kubelet/src/pod/mod.rs, crates/kubelet/src/pod/status.rs, crates/kubelet/src/provider/mod.rs, crates/kubelet/src/secret/mod.rs, crates/kubelet/src/state/common/resources.rs, crates/kubelet/src/volume/configmap.rs, crates/kubelet/src/volume/downward.rs, crates/kubelet/src/volume/mod.rs, crates/kubelet/src/volume/persistentvolumeclaim.rs, crates/kubelet/src/volume/projected.rs, crates/kubelet/src/volume/secret.rs, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/states/container/waiting.rs, tests/assert.rs, tests/expectations.rs, tests/integration_tests.rs
As k8s-openapi reverted in https://github.com/Arnavion/k8s-openapi/commit/f0fda041e401e7d3bbb39b19ff305e258688728d to its use of `Option<>`, this commit reverts most of 4846df7982fe4649e2e038ed7f69b04f148063c0.
Also update kube and kube-runtime to 0.60.
**Note:** This depends on krator PR: https://github.com/krator-rs/krator/pull/49 so we must wait for this PR to be merged and a krator release done.
Fixes #660
=> Update k8s-openapi to 0.13 and k8s 1.22

crates/oci-distribution/src/client.rs
Supersedes: https://github.com/krustlet/krustlet/pull/617
There are several relevant commits:
- https://github.com/krustlet/krustlet/pull/670/commits/6769e723e2217dd3000c6a32286cedec09e5d58e: this is a fix for servers that are strict about the first query argument on the URI. JFrog is strict as GitHub registry in this sense, and they reject a request of the form `uri&query=`. They expect `uri?query1=<value>&query2=<value>`.
- https://github.com/krustlet/krustlet/pull/670/commits/b64f3e389ed825b83b0a6762450832b214065e58: building block for the next commit. This exposes a `RequestBuilderWrapper` type that can be used to initialize from a client, with a certain operation on it, and that allows to execute modifier functions that might need client information. When done, this type can be …
=> oci-distribution: fix push to JFrog (and ghcr.io)

crates/kubelet/src/kubelet.rs, tests/device_plugin/mod.rs
'u64::MAX' is the recommended way to represent the largest number of u64 type(reference: https://doc.rust-lang.org/std/u64/constant.MAX.html) and 'std::u64::MAX' is now deprecated in a future Rust version.
Signed-off-by: zyy17 <zyylsxm@gmail.com>
=> Modify 'std::u64::MAX' to 'u64::MAX'
