krustlet/krustlet

CONTRIBUTING.md, README.md
=> chore(*): Adds code of conduct information to contributing and README

.github/workflows/build.yml, justfile, src/kubelet.rs, src/pod.rs, src/server.rs, src/wasm.rs
=> fix(*): Fixes various Clippy issues and adds an Action pipeline

.github/workflows/build.yml
Just a few suggestions that @rylev commented on #11 after merge
=> fix(*): Addresses some follow up from the original PR

crates/kubelet/src/kubelet.rs
This just adds a little bit of inline docs in places that I felt I hadn't covered before.
See also #13, which I filed while writing this.
=> add a few inline docs to the code

Cargo.lock, crates/wascc-provider/Cargo.toml
wascc-provider doesn't need wasi or wasmtime deps.
=> remove wasm and wasi crate dependencies

crates/kubelet/src/kubelet.rs, crates/kubelet/src/node.rs, crates/kubelet/src/server.rs
Some small changes I noticed when reading the code for the first time
=> A few less allocations

.dockerignore, README.md, docs/README.md, docs/community/README.md, docs/community/code-of-conduct.md, docs/community/developers.md, docs/intro/README.md, docs/intro/install.md, docs/intro/readnext.md, docs/intro/tutorial01.md, docs/intro/tutorial02.md, docs/intro/tutorial03.md, docs/intro/tutorial04.md, docs/topics/README.md, docs/topics/architecture.md, examples/greet.yaml
=> introduce and organize the documentation for Krustlet

crates/kubelet/src/node.rs
See #5 relating to the issue this attempts to workaround.
Rather than serialize a `LeaseSpec` which has a variable sized timestamp
formatting, this forces the timestamps to the six digits of subsecond precision
currently required by the k8s API.
=> Implement workaround for LeaseSpec serialization issue.

crates/kubelet/src/kubelet.rs, src/krustlet-wascc.rs, src/krustlet-wasi.rs
=> remove namespace from Kubelet::new()

Cargo.lock, crates/wascc-provider/Cargo.toml, crates/wascc-provider/src/lib.rs, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/lib.rs, crates/wasi-provider/src/wasi_runtime.rs
Removes more instances of blocking that will gum up the tokio runtime. 
This fixes #21
=> Less blocking

crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs
Both WasCC and WASI will now spin up a running wasmtime instance/actor
for each container in a pod. Right now the actual module is still
hard coded, but will be replaced when the work around OCI is done.
Closes #24
=> feat(*): Adds support for multiple containers

crates/oci-distribution/src/lib.rs
=> change string to &str

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/kubelet/src/config.rs, crates/kubelet/src/kubelet.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/server.rs, crates/oci-distribution/Cargo.toml, crates/oci-distribution/src/lib.rs, crates/oci-distribution/src/reference.rs, crates/wascc-provider/Cargo.toml, crates/wascc-provider/src/lib.rs, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/handle.rs, crates/wasi-provider/src/lib.rs, crates/wasi-provider/src/wasi_runtime.rs, src/krustlet-wascc.rs, src/krustlet-wasi.rs
=> Switch to anyhow

crates/kubelet/src/kubelet.rs, crates/kubelet/src/pod.rs, crates/wasi-provider/src/lib.rs
@thomastaylor312 do we believe this is the right thing to do?
=> Require name

.github/workflows/build.yml, Cargo.lock, Cargo.toml, crates/kubelet/src/config.rs, crates/kubelet/src/node.rs, docs/community/developers.md, docs/intro/tutorial04.md, justfile, tests/integration_tests.rs
=> add e2e tests

.github/workflows/build.yml, Cargo.lock, Cargo.toml, crates/kubelet/src/server.rs, tests/integration_tests.rs
=> feat(e2e): wait for pod to enter the Running state

Cargo.lock, crates/oci-distribution/Cargo.toml, crates/oci-distribution/src/lib.rs
=> oci_distribution::Client::pull

crates/oci-distribution/src/lib.rs, crates/oci-distribution/src/reference.rs
=> Configure protocol of OCI Client

Cargo.lock, crates/oci-distribution/src/lib.rs, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/lib.rs, examples/greet-wascc.yaml, examples/greet-wasi.yaml, examples/greet.yaml, src/krustlet-wasi.rs
=> Pull image in the wasi provider instead of hard coded

Cargo.lock, crates/kubelet/src/config.rs, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/lib.rs, src/krustlet-wasi.rs
Allows a user to specify what directory logs and modules should be downloaded to
=> feat(*): Adds configurable data path

demos/wasi/hello-world-c/.gitignore, demos/wasi/hello-world-c/README.md, demos/wasi/hello-world-c/demo.c, demos/wasi/hello-world-c/k8s.yaml
Also contains a tiny fix in the webassembly README
Closes #104
=> feat(demos): Adds WASI demo written in C

demos/wasi/hello-world-assemblyscript/assembly/index.ts
=> Simplfy imports

Cargo.lock, crates/kubelet/Cargo.toml, crates/kubelet/src/server.rs
Hopefully this helps understand some more of the parts around hyper, I did realize that we don't actually provide a proper abstractions for accepting tls on the server side so I tried to write it in a more procedural manner. Let me know if this helps! 
cc @rylev 
Signed-off-by: Lucio Franco <luciofranco14@gmail.com>
=> Improve hyper server usage

README.md
Also clarifies that this is no longer just a proof of concept
=> docs(README): Adds meeting time to README

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/kubelet/src/image_client.rs, crates/kubelet/src/kubelet.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/module_store.rs, crates/kubelet/src/node.rs, crates/kubelet/src/pod.rs, crates/kubelet/src/provider.rs, crates/wascc-provider/Cargo.toml, crates/wascc-provider/src/lib.rs, crates/wasi-provider/Cargo.toml, crates/wasi-provider/src/handle.rs, crates/wasi-provider/src/lib.rs, src/krustlet-wascc.rs, src/krustlet-wasi.rs, tests/integration_tests.rs
There's no need to pass a client to every Provider method. If the implementing type needs a client they can provide it themselves.
=> No client in provider

docs/intro/install.md
=> docs(install): add install links

crates/wasi-provider/src/handle.rs, crates/wasi-provider/src/lib.rs
These panics were causing the process to crash when a pod was deleted.
We now just log when we attempt to delete a pod and let the pod be
deleted from the API
Closes #129
=> fix(wasi): Removes unimplemented panics

docs/howto/krustlet-on-aks.md
=> ref(howto): formatting

docs/howto/krustlet-on-aks.md
with the 0.1.0 MVP planned to be released sometime soon, it'd be easier to link to the install guide to reference how to install Krustlet.
=> docs(aks): link to install guide

docs/howto/krustlet-on-minikube.md, docs/howto/kubernetes-on-minikube.md
=> docs(howto): krustlet on minikube

docs/howto/krustlet-on-kind.md
=> docs(howto): krustlet on KinD

crates/kubelet/src/node.rs
=> fix(kubelet): Attempts a lease update instead of failing on restart

docs/howto/krustlet-on-kind.md
thanks to @jingweno for the tip.
=> docs(kind): special instructions for Docker Desktop for Mac

.github/workflows/build.yml, crates/wascc-provider/src/lib.rs, docs/intro/install.md, justfile
This is just temporary for version 0.1 because we'll be able to statically
compile once we upgrade wascc
=> feat(wascc): Adds configurable object file paths

.github/workflows/release.yml
=> feat(.github): add waSCC dylibs to package

docs/howto/README.md, docs/howto/krustlet-with-inlets.md
=> fix(howto): formatting

crates/kubelet/src/kubelet.rs, crates/kubelet/src/node.rs, crates/kubelet/src/server.rs
=> Retry actions on nodes

docs/intro/quickstart.md
=> feat(docs): add link to AKS tutorial

docs/intro/README.md, docs/intro/intro.md, docs/topics/README.md, docs/topics/glossary.md
=> docs(intro): What is Krustlet?

Cargo.lock, Cargo.toml, crates/kubelet/src/handle.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/pod.rs, crates/kubelet/src/volumes.rs, crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs, crates/wasi-provider/src/wasi_runtime.rs, tests/integration_tests.rs
=> feat(*): Adds volume support to wasi

Cargo.lock, Cargo.toml, crates/kubelet/src/config.rs, crates/kubelet/src/volumes.rs, tests/integration_tests.rs
Also fixes a few clippy issues we missed earlier.
Closes #179
=> feat(kubelet): Adds host path volume support

.github/workflows/release.yml, docs/intro/install.md
=> fix(release): lowercase OS name

crates/kubelet/src/config.rs
Small cleanup I noticed when reviewing old PRs.
=> Small cleanup

.github/workflows/build.yml, .github/workflows/release.yml
=> fix the lowercasing of the OS name

.github/workflows/release.yml
=> fix indentation

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml
This release contains the "refresh token" feature.
Closes #187
=> chore(*): Updates kube to 0.33

.github/workflows/build.yml, .github/workflows/release.yml
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
=> skip CI on doc changes

docs/intro/quickstart.md
=> feat(quickstart): add links to HOWTO guides

docs/howto/krustlet-on-gke.md, docs/howto/kubernetes-on-gke.md
=> Krustlet on Google Kubernetes Engine

crates/wascc-provider/src/lib.rs
When deleting a pod before, we left the capabilities bound, which
caused errors when trying to recreate the same pod
Closes #243
=> fix(wascc): Properly unbinds volumes from actors

tests/integration_tests.rs
=> Clean up WASI test resources even if test fails

.github/workflows/release.yml, Cargo.toml, crates/kubelet/Cargo.toml, crates/oci-distribution/Cargo.toml, crates/wascc-logging/Cargo.toml, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml, demos/wasi/hello-world-assemblyscript/k8s.yaml, demos/wasi/hello-world-c/k8s.yaml, demos/wasi/hello-world-rust/k8s.yaml, docs/howto/krustlet-on-aks.md, docs/intro/install.md, docs/topics/architecture.md
This contains various and sundry doc updates and clarifications for
0.2. I fixed and/or added a few things while I went through the docs
and updated the GH action to push each crate separately.
This SHOULD NOT be merged until right before we cut 0.2
=> docs(*): Various doc updates for 0.2

.github/workflows/release.yml, crates/kubelet/Cargo.toml
Also removes an errant field in the kubelet Cargo.toml and fixes some ordering
issues
=> fix(*): Makes crate publish happen on tags

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml
I tested this with a local instance of docs.rs
=> fix(kubelet): Adds proper features for docs build

.github/workflows/build.yml, Cargo.lock, crates/kubelet/Cargo.toml, crates/kubelet/src/config.rs, crates/kubelet/src/logs.rs, crates/kubelet/src/node.rs, crates/kubelet/src/server.rs
=> Improve path parsing and error handling for kubelet API.

Cargo.lock, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml
=> bump wascc-host to 0.7

crates/kubelet/Cargo.toml, crates/kubelet/README.md, crates/oci-distribution/README.md
=> add docs.rs links for kubelet and oci-distribution

LICENSE
related to #269. This corrects the copyright owners until legal assesses whether it's worth switching over to MIT.
=> fix(LICENSE): update copyright authors to Microsoft

hack/bootstrap.sh
* Add LC_CTYPE to avoid `tr: Illegal byte sequence` error
* Support gnu and BSD date commands
* Refactor copy pasta
=> fix(hack/bootstrap.sh): support gnu and BSD

crates/wasi-provider/src/lib.rs, tests/integration_tests.rs
=> Pass container arguments to WASI module

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml
This should not be merged until right before we cut 0.3
=> chore(*): Updates crate versions for 0.3

Cargo.lock, Cargo.toml, crates/kubelet/Cargo.toml, crates/oci-distribution/Cargo.toml, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml
=> bump oci-distribution to 0.2.0

docs/community/README.md, docs/community/release-checklist.md
=> docs: add release checklist

README.md
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
=> Update Community section of README.md

crates/kubelet/src/bootstrapping/mod.rs, src/krustlet-wascc.rs, src/krustlet-wasi.rs
The bootstrap now checks to make sure the certs were approved before
writing anything to a file. I also fixed log init so that it happens
before bootstrap
Fixes #300
=> fix(bootstrap): Makes sure to not write empty file

crates/wascc-provider/src/lib.rs
Fixes #282.
At least for the case of container args in the pod spec; there may be other validation issues we need to tighten up too.
NOTE: What I've done for testing is just to add unit tests for the "do we know how to run this pod" stuff; I have not added an integration test to verify that the waSCC provider correctly calls and honours that function, because adding integration tests is laborious, and Hey It Is Only One Line And Nothing Can Possibly Go Wrong TM.  It would be good to refactor the waSCC integration tests to make it easier to add more tests; let me know if you'd like me to do this as part of this PR.
=> waSCC can't honour container args

crates/kubelet/src/pod/handle.rs, crates/kubelet/src/pod/mod.rs, crates/wascc-provider/src/lib.rs
We had a few Clippy lints sneak into master.  This just addresses them.
=> Pacify Clippy

crates/kubelet/src/container/handle.rs, crates/kubelet/src/container/mod.rs, crates/kubelet/src/node/mod.rs, crates/kubelet/src/pod/handle.rs, crates/kubelet/src/pod/mod.rs, crates/kubelet/src/pod/status.rs, crates/wascc-provider/src/lib.rs, crates/wasi-provider/src/lib.rs, tests/expectations.rs, tests/integration_tests.rs
=> Fix reporting of init container statuses

Cargo.lock, crates/wascc-logging/Cargo.toml, crates/wascc-logging/src/lib.rs, crates/wascc-provider/Cargo.toml
=> bump wascc-host to 0.10

docs/howto/README.md, docs/howto/krustlet-on-wsl2.md, docs/howto/wasm.md
Because I done got bitten and I don't want other folks to get bitten too.
=> Document tolerations and node affinities for WASM

crates/oci-distribution/src/client.rs
Calls to fetch_manifest_digest would not fetch the auth token before fetching the manifest digest, causing the call to fail due to an authentication failure.
Several functions were noticed as marked public. Those should not be made available for external use.
Big thanks to @radu-matei for helping me with identifying the issue.
Closes #311
=> fix(oci-distribution): check for auth token before fetching manifest digest

crates/kubelet/src/volume/mod.rs, demos/wasi/wasmerciser/Cargo.lock, demos/wasi/wasmerciser/Cargo.toml, demos/wasi/wasmerciser/src/main.rs, demos/wasi/wasmerciser/src/syntax.rs, tests/assert.rs, tests/integration_tests.rs, tests/oneclick/src/main.rs, tests/pod_builder.rs, tests/test_resource_manager.rs
=> Mount individual items from configmaps or secrets

crates/kubelet/src/volume/mod.rs
This was meant to be part of #354 but I forgot to push it before merging!
=> Fix wording of decision whether to mount a config item

.github/workflows/build.yml, justfile, tests/integration_tests.rs, tests/pod_builder.rs, tests/test_resource_manager.rs
The testing work for image pull secrets that we deferred to avoid rebase woes
=> Image pull secrets CI test

crates/kubelet/src/backoff/mod.rs, crates/kubelet/src/lib.rs, crates/wascc-provider/src/lib.rs, crates/wascc-provider/src/states/crash_loop_backoff.rs, crates/wascc-provider/src/states/image_pull.rs, crates/wascc-provider/src/states/image_pull_backoff.rs, crates/wasi-provider/src/lib.rs, crates/wasi-provider/src/states/crash_loop_backoff.rs, crates/wasi-provider/src/states/image_pull.rs, crates/wasi-provider/src/states/image_pull_backoff.rs, crates/wasi-provider/src/states/initializing.rs
=> Exponential backoff

.gitignore
=> Exclude oneclick trace files from Git

crates/kubelet/src/pod/handle.rs, crates/kubelet/src/state.rs, crates/wascc-provider/src/states.rs, crates/wascc-provider/src/states/crash_loop_backoff.rs, crates/wascc-provider/src/states/error.rs, crates/wascc-provider/src/states/finished.rs, crates/wascc-provider/src/states/image_pull.rs, crates/wascc-provider/src/states/image_pull_backoff.rs, crates/wascc-provider/src/states/registered.rs, crates/wascc-provider/src/states/running.rs, crates/wascc-provider/src/states/starting.rs, crates/wascc-provider/src/states/terminated.rs, crates/wascc-provider/src/states/volume_mount.rs, crates/wasi-provider/src/states.rs, crates/wasi-provider/src/states/completed.rs, crates/wasi-provider/src/states/crash_loop_backoff.rs, crates/wasi-provider/src/states/error.rs, crates/wasi-provider/src/states/image_pull.rs, crates/wasi-provider/src/states/image_pull_backoff.rs, crates/wasi-provider/src/states/initializing.rs, crates/wasi-provider/src/states/registered.rs, crates/wasi-provider/src/states/running.rs, crates/wasi-provider/src/states/starting.rs, crates/wasi-provider/src/states/terminated.rs, crates/wasi-provider/src/states/volume_mount.rs, krustlet-wascc-e2e.stderr.txt, krustlet-wasi-e2e.stderr.txt
Fixes #390.
There's currently more boilerplate around error handling than is nice.  I looked at some macro-based shortcuts for these, but haven't yet found anything that looks nice.  I'll keep tinkering though!
=> Infallible state handlers

Cargo.toml, crates/kubelet/Cargo.toml, crates/oci-distribution/Cargo.toml, crates/wascc-logging/Cargo.toml, crates/wascc-provider/Cargo.toml, crates/wasi-provider/Cargo.toml
Because we forgot to add him when became a core maintainer
=> chore(*): Adds Kevin as an author in all Cargo.toml files

.github/workflows/build.yml, crates/oci-distribution/src/reference.rs, src/krustlet-wascc.rs, src/krustlet-wasi.rs
Rust `1.47.0` appears to have fixed this issue.
=> Remove Type Length Patch

crates/kubelet/src/kubelet.rs
We weren't actually boxing our fused futures so there was still a bunch
of stuff pinned on the stack. This was causing stack overflow problems
on Windows
=> fix(kubelet): Make sure we actually box

crates/kubelet/src/store/oci/file.rs, crates/oci-distribution/src/client.rs
=> fix(oci-distribution): return content of all layers

.github/workflows/build.yml, .github/workflows/release.yml, Cargo.toml
=> cross-compile for aarch64

docs/intro/tutorial02.md
=> fix markdownlint comments

docs/intro/tutorial01.md
=> use --release

contrib/azure/azuredeploy.json, contrib/azure/azuredeploy.parameters.json
fixing up a few stray links missed with #448.
=> update url links

.github/workflows/build.yml
=> bump configurator to v0.0.5

docs/howto/krustlet-on-gke.md, docs/howto/krustlet-on-kind.md, docs/howto/krustlet-on-microk8s.md, docs/howto/krustlet-on-minikube.md, docs/howto/krustlet-with-inlets.md
Just finishing the removal started in #447 because I had the same issue because of the flags
=> Remove unused flags from howto guides

contrib/azure/azuredeploy.json
=> Patch Azure One Click Deploy

docs/howto/krustlet-on-do.md, docs/howto/kubernetes-on-do.md
Instructions for creating Managed Kubernetes cluster on [DigitalOcean](https://digitalocean.com) and deploying Krustlet to a Droplet.
=> Running Krustlet on DigitalOcean

docs/intro/tutorial02.md, docs/intro/tutorial03.md
This pull requests outlines that you now need an image pull secret in Kubernetes and how you create it for the Azure container registry.
=> Added text on creating an image pull secret for the tutorial

.github/workflows/build.yml, .github/workflows/lint.yml
It doesn't appear to be possible to skip some jobs based on what paths were updated, so I split lints out into a new Action that runs for everything. 
cc #490 
Closes #493
=> Lint docs for all PRs and branches

.github/workflows/build.yml, docs/intro/tutorial02.md
=> Move UI test to separate Job

crates/kubelet/src/grpc_sock/client.rs, crates/kubelet/src/grpc_sock/unix/mod.rs, crates/kubelet/src/grpc_sock/windows/mod.rs, crates/kubelet/src/plugin_watcher/mod.rs
=> chore(grpc): Adds `now_or_never` to remove need for polling in Windows

docs/howto/assets/bootstrap.sh
- fix bootstrap script with busybox date
- the script is tested on NixOS with BusyBox v1.32.0
=> fix(bootstrap): Handle busybox date

Cargo.toml, crates/krator/Cargo.toml, crates/kubelet/Cargo.toml
=> chore(*): Updates openapi objects to k8s 1.20

crates/kubelet/src/volume/persistentvolumeclaim.rs
=> Wrappes creation of temporary directory with tokio::task::spawn_blocking to avoid blocking IO in an async context

.github/workflows/build.yml
This was causing a spurious failure when e2e tests failed
=> fix(e2e): Removes old log cat step

crates/oci-distribution/src/client.rs
Closes #495 
I've preserved the commit history and tests from #525, but I cannot push to that branch so I'm opening a new PR. 
cc @jdolitsky
=> Support DockerHub OCI Authentication

crates/kubelet/src/volume/mod.rs, crates/kubelet/src/volume/persistentvolumeclaim.rs
This PR pretty much handles all but one of the outstanding TODOs for CSI.
Please note that e2e tests are not handled here and will be covered in another
PR (see #579). The other TODO is covered in #580.
Closes #552
=> feat(csi): Adds full validation and fixes TODOs

.github/workflows/build.yml, crates/kubelet/src/bootstrapping/mod.rs
=> fix(bootstrap): Ensures directories are created before writing

crates/kubelet/src/log/mod.rs
Added some parameters to the internal processing of a request for logs:
- since
- since_seconds
- previous
- timestamps
- limit_bytes
More details on these can be found at https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#logs
fixes #590
=> Added parsing of more parameters to the internal processing of a request for logs

crates/krator-derive/src/admission.rs
=> Fix clippy warnings

crates/oci-distribution/src/errors.rs
According to the [OCI distribution
specification](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#error-codes),
both the `detail` and `message` fields are optional. Some
registries (such as `us.gcr.io`) are not reporting the `detail` field
back in light of certain errors. The `message` field could also be
omitted while still following the spec.
Implement serde defaulting using `Default::default()` if any of these
attributes are missing on the wire.
=> oci-distribution: OCI error detail is optional

demos/wasi/wasmerciser/Cargo.lock, demos/wasi/wasmerciser/Cargo.toml, tests/pod_builder.rs
This bumps the image to 0.3. I have also built it and pushed the image up to
both ACRs.
=> chore(*): Bump wasmerciser image

crates/kubelet/src/kubelet.rs, crates/kubelet/src/lib.rs, crates/kubelet/src/provider/mod.rs, crates/kubelet/src/state/common/mod.rs, crates/kubelet/src/state/common/volume_mount.rs, crates/wasi-provider/src/lib.rs
This still isn't super pretty (as you can't overload impls in Rust), but
at least things are consolidated. I can combine these traits if desired
but I left them separate in case we wanted to improve ergonomics further
in the future
Closes #524
=> feat(provider): Adds traits for volume and plugin stuff

crates/oci-distribution/src/client.rs
While using the 'docker.io' namespace, DockerHub is actually using
registry-1.docker.io as registry.
Docker manually overrides it when accessing the registry so do it here
as well.
Fix #596
Are we happy changing the output of `reference.whole()` and `reference.registry()`?
The alternative would be to keep them untouched, add a  `reference.registry_override()` or something and use it in most place of the code instead of `reference.registry()`, but that would be a more invasive change.
=> oci-distribution: use DockerHub actual registry

crates/kubelet/src/resources/device_plugin_manager/manager.rs, crates/kubelet/src/volume/configmap.rs, crates/kubelet/src/volume/persistentvolumeclaim.rs, crates/kubelet/src/volume/secret.rs
There were some places where we needed to unwrap the join error _and_
the Result. Also removed an import that was no longer needed
=> fix(*): Handles results in windows code

crates/kubelet/src/bootstrapping/mod.rs
On Unix file systems the mode of the private key file is set to 0o600. On other file systems the permissions remain unchanged.
Fixes #639
=> Restrict permissions of private key file

crates/kubelet/src/bootstrapping/mod.rs
@thomastaylor312 hello there,
tried to fix #642 
please let me know if Im on the right track or totally off ☹️
=> added steps to support bootstrapping by loading filepath to CA

crates/kubelet/src/bootstrapping/mod.rs
=> WIP: Stubbed out handling for a 409 on csrs create

.vscode/launch.json
Signed-off-by: zyy17 <zyylsxm@gmail.com>
=> Refractor: refine naming from 'Kubelet' to 'Krustlet'
